// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmtvxgvfxyyxewczikor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttdHZ4Z3ZmeHl5eGV3Y3ppa29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MDM4MjYsImV4cCI6MjA3NjE3OTgyNn0.BqRAxYcIeI8ek5IjKrsAWCrXoLabX8nz_oR3B40-zvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});